params:
  env:
    name: Compression-v0
    seed: 123
  loss:
    name: SHACLoss
    target_file: Compression.pkl
    weight:
      density: 0
      sdf: 21
      contact: 0
      is_soft_contact: False

  config:
    actor_learning_rate: 5e-5 # adam
    critic_learning_rate: 1e-4 # adam
    lr_schedule: linear # ['constant', 'linear']
    target_critic_alpha: 0.1
    critic_iterations: 128
    critic_method: td-lambda # ['td-lambda', 'one-step']
    lam: 0.99
    num_batch: 1
    gamma: 0.99
    betas: [0.9, 0.999] # adam
    max_epochs: 2000
    grad_norm: 1
    truncate_grads: True
    num_actors: 2
    save_interval: 400
    device: cuda:0



