params:
  env:
    name: Flow-v0
    seed: 123
  loss:
    name: PPOLoss
    target_file: Flow.pkl
    weight:
      density: 21
      sdf: 21
      contact: 0
      is_soft_contact: False

  config:
    deterministic_eval: True
    action_scaling: False
    ReplayBufferSize: 20000
    max_epochs: 100
    step_per_epochs: 896
    repeat_per_collect: 4
    episode_per_test: 5
    batch_size: 224
    step_per_collect: 896
    num_envs: 2
    lr: 0.00005
    betas: [0.9, 0.999]
    device: cuda:0



