params:
  env:
    name: Shear-v0
    seed: 123
  loss:
    name: PPOLoss
    target_file: Shear.pkl
    weight:
      density: 0
      sdf: 21
      contact: 0
      is_soft_contact: False

  config:
    deterministic_eval: True
    action_scaling: False
    ReplayBufferSize: 20000
    max_epochs: 200
    step_per_epochs: 1280
    repeat_per_collect: 10
    episode_per_test: 5
    batch_size: 128
    step_per_collect: 1280
    num_envs: 2
    lr: 0.00005
    betas: [0.9, 0.999]
    device: cuda:0